language: r
cache: packages

env:
  global:
    - secure: "gZMbIHd+NPTAnrSN7VDk+Ej79wF9jeytf45Bapy8Y0CS0fCX7OrUwocSW79qypWHL1AvYoVsKYkjaLtq3r7MDa30EmVL5bKcNmAaSxYKu38yU1L3F9l3zB4v3bns6hiFtQjAWSs7qD+8ynpVtDfKQit0aefqiqbR3RmA1XEMtkBz/LKmJZWAMDwRMvZko2hdmPN1tvTvxLhRvi4gKPCz+FQfGcailR+3axom1qx6EzSJ1+oA9XICWAGp8t0ucvQTzNMmORIOXY+tRoLcLhoek3ODNJnOEUn4kDqSGFODtJjHLwQp4/Ru1W1p8Y7Qlnn1ao8Jl4qCouBSZj5IY9+gB0KZmxY01SEM2rf+9SjUPqbcEk76YTYrDDPWpsl0yWMAaU3Bt6hBMzpuhK5AMMwB7RThed/yMJqAjS2lquiAkwaMRDmw+iTg6QM656oM3jTH1MFrDE2H7HFmhOoHXsHIV0z6+1OkFTUBgIr39IlqjaBDqXB/NFiRFD1ikq5wQmwNcPEYounmWPEvPfyY3wK6gvNsZmbAJh6mlH7WyqgpmJmwk8PKhEjJ//5b+7lppDDyexud7E5UhxTXnIzGDdYCJ2JhcaQbAmKYCJ7bLLxbSkZJSrksbTb6w7cuFg3n/FE6Bm+IHxwaQ76QpZ+v1jJzWs1lLmZocuFfvW7qjc/llqs="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
