language: r
cache: packages

env:
  global:
    - secure: "ExkX9rOKEyROoqYFkal3NuIur8ZDdDK2dC2y8/35YClBZRdjIxBxbqdDiXRuNyS9cRu6Jj8DHZzfAz1U/kBJJNdCu+lqAevdKxBJp8NRP6RHoz9CQFolasqMSz0Qw+OILL+4byFQ1xFJFamV5mcGnWJD50gMjeE198D7dxE7JOj/YZxDnu0TEu4FBPdBXwV0e2Phux+Oq6W7z/ZuXSVDCgemSAM4P2/QHJiCez+G27UUThOxoG6bvlgOMhzhetHJegHUVic+sYxpZiyPPAYEPZhisPi9CEmj+6B0UCdenWboJ+RpeLihdLyjiBxKyjRieOtXlf1T4i0mj8cfoyrqkqYqWGNvrQTfMg3WovVF7+Emx/0rIJDgvebevEpZF4h5m8JMZPfVYkfV7lYszLP+Oor0xK5XwvXH7xwFZ+dhN9wCPqUkKmzZBks8ps+7oqjR1zt7WWLSlObV9BO3fE0PCJiox6m4IAR+ahZ6QnZG30MPeic7aEsudQlq+cvTvVhsCcJAALZE/Omo3JEO7aAn4dahk/Ewe1LRw2dmWAefiK82JIvW3a27nWQATV5o+Fr2DR1gZIW4dYTK+aaIAq+iWQJbOiPphDWhBimy08+s/eyU7DkZvR9mzgnPfvtf3e2kgboXaWvjfoiUUbY+tYONhXpkZay6TAH3VJntxLo8NMQ="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
